apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "OperandRequest",
          "metadata": {
            "name": "ibm-commonui-request"
          },
          "spec": {
            "requests": [
              {
                "operands": [
                  {
                    "name": "ibm-iam-operator"
                  },
                  {
                    "name": "ibm-management-ingress-operator"
                  },
                  {
                    "name": "ibm-platform-api-operator"
                  }
                ],
                "registry": "common-service"
              }
            ]
          }
        },
        {
          "apiVersion": "operators.ibm.com/v1alpha1",
          "kind": "CommonWebUI",
          "metadata": {
            "name": "example-commonwebui"
          },
          "spec": {
            "commonWebUIConfig": {
              "cpuLimits": "300m",
              "cpuMemory": "200Mi",
              "imageRegistry": "quay.io/opencloudio",
              "imageTag": "1.2.0",
              "ingressPath": "/common-nav",
              "requestLimits": "300m",
              "requestMemory": "200Mi",
              "serviceName": "common-web-ui"
            },
            "globalUIConfig": {
              "authServiceURL": "https://icp-management-ingress:443/idauth",
              "cloudPakVersion": "3.4.0",
              "clusterName": "mycluster",
              "defaultAdminUser": "admin",
              "defaultAuth": "",
              "enterpriseLDAP": "",
              "enterpriseSAML": "",
              "identityProviderURL": "https://icp-management-ingress:443/idprovider",
              "osAuth": "",
              "routerHTTPSPort": 443,
              "routerURL": "https://icp-management-ingress:443",
              "sessionPollingInterval": 5000
            },
            "operatorVersion": "1.2.0"
          }
        }
      ]
    capabilities: Seamless Upgrades
    categories: Security
    certified: "false"
    containerImage: quay.io/opencloudio/ibm-commonui-operator:1.2.0
    description: The IBM Common Web UI delivers the common header API and the
      identity and access pages for IBM Cloud Platform Common Services.
    repository: https://github.com/IBM/ibm-commonui-operator
    support: IBM
  name: ibm-commonui-operator.v1.2.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CommonWebUI is the Schema for the commonwebuis API
      kind: CommonWebUI
      name: commonwebuis.operators.ibm.com
      version: v1alpha1
      displayName: CommonWebUI service
      resources:
      - kind: Service
        name: ''
        version: v1
      - kind: Ingress
        name: ''
        version: v1
      - kind: Daemonset
        name: ''
        version: v1
      - kind: Pod
        name: ''
        version: v1
      - kind: ConfigMap
        name: ''
        version: v1
      - kind: LegacyHeader
        name: ''
        version: 'v1alpha1'
      - kind: ReplicaSet
        name: ''
        version: v1
      - kind: CommonWebUI
        name: ''
        version: 'v1alpha1'
      - kind: Deployment
        name: ''
        version: v1
      specDescriptors:
        - description: Configuration parameters for common web ui specific to the service
          displayName: Common Web UI Configuration
          path: commonWebUIConfig
        - description: Configuration parameters the service will consume particular to the cluster
          displayName: Cluster configuration parameters
          path: globalUIConfig
        - description: Version for the installed operator
          displayName: Operator Version 
          path: operatorVersion
      statusDescriptors:
        - description: Displays names of pods associated with the Common Web UI service
          displayName: Pod Names
          path: nodes
    - description: LegacyHeader is the Schema for the legacyHeader API
      kind: LegacyHeader
      name: legacyheaders.operators.ibm.com
      version: v1alpha1
      displayName: LegacyHeader service
      resources:
        - kind: Service
          name: ''
          version: v1
        - kind: Ingress
          name: ''
          version: v1
        - kind: Daemonset
          name: ''
          version: v1
        - kind: Pod
          name: ''
          version: v1
        - kind: ConfigMap
          name: ''
          version: v1
        - kind: LegacyHeader
          name: ''
          version: 'v1alpha1'
        - kind: ReplicaSet
          name: ''
          version: v1
        - kind: CommonWebUI
          name: ''
          version: 'v1alpha1'
        - kind: Deployment
          name: ''
          version: v1
      specDescriptors:
        - description: Configuration parameters for the legacy header service
          displayName: Legacy header configuration parameters
          path: legacyConfig
        - description: Configuration parameters the service will consume particular to the cluster
          displayName: Cluster configuration parameters
          path: legacyGlobalUIConfig
        - description: Version for the installed operator
          displayName: Operator Version 
          path: operatorVersion
      statusDescriptors:
        - description: Displays names of pods associated with the Legacy Header service
          displayName: Pod Names
          path: nodes
  description: "**Important:** Do not install this operator directly. Only install this operator using the IBM Common Services Operator. 
    For more information about installing this operator and other Common Services operators, see [Installer documentation](http://ibm.biz/cpcs_opinstall).\n\n 
    If you are using this operator as part of an IBM Cloud Pak, see the documentation for that IBM Cloud Pak to learn more about how to install and use the operator 
    service. For more information about IBM Cloud Paks, see [IBM Cloud Paks that use Common Services](http://ibm.biz/cpcs_cloudpaks).\n\n 
    You can use the ibm-commonui-operator to install the Common Web UI service for the IBM Cloud Platform Common Services and access 
    the Common Web UI console. You can use the Common Web UI console to access information and features from other IBM Cloud Platform 
    Common Services or IBM Cloud Paks that you install. \n\nFor more information about the available IBM Cloud Platform Common Services, see
     the [IBM Knowledge Center](http://ibm.biz/cpcsdocs). \n## Supported platforms \n\n Red Hat OpenShift Container Platform 4.2 or 
     newer installed on one of the following platforms: \n\n- Linux x86_64 \n- Linux on Power (ppc64le) \n- Linux on IBM Z and 
     LinuxONE \n## Prerequisites\n\n The Common Web UI service has dependencies on other IBM Cloud Platform Common Services. Before you install this operator, 
     you need to first install the operator dependencies and prerequisites: \n For the list of operator dependencies, see the IBM Knowledge Center 
     [Common Services dependencies documentation](http://ibm.biz/cpcs_opdependencies). \n For the list of prerequisites for installing the operator, see the 
     IBM Knowledge Center [Preparing to install services documentation](http://ibm.biz/cpcs_opinstprereq). \n## Documentation \n\n To install the operator 
     with the IBM Common Services Operator follow the the installation and configuration instructions within the IBM Knowledge Center. \n- If you are using the 
     operator as part of an IBM Cloud Pak, see the documentation for that IBM Cloud Pak, for a list of IBM Cloud Paks, see 
     [IBM Cloud Paks that use Common Services](http://ibm.biz/cpcs_cloudpaks). \n- If you are using the operator with an IBM Containerized Software, 
     see the IBM Cloud Platform Common Services Knowledge Center [Installer documentation](http://ibm.biz/cpcs_opinstall)."
  displayName: IBM Common UI Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - get
          - list
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: ibm-commonui-operator
      deployments:
      - name: ibm-commonui-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-commonui-operator
          strategy: {}
          template:
            metadata:
              annotations:
                openshift.io/scc: restricted
                productID: 068a62892a1e4db39641342e592daa25
                productMetric: FREE
                productName: IBM Cloud Platform Common Services
                productVersion: 3.4.0
              labels:
                name: ibm-commonui-operator
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: beta.kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - ppc64le
                        - s390x
              containers:
              - command:
                - ibm-commonui-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-commonui-operator
                - name: COMMON_WEB_UI_IMAGE_TAG_OR_SHA
                  value: "1.2.0"
                - name: LEGACYHEADER_IMAGE_TAG_OR_SHA
                  value: "3.2.4"
                image: quay.io/opencloudio/ibm-commonui-operator:1.2.0
                imagePullPolicy: Always
                name: ibm-commonui-operator
                resources:
                  limits:
                    cpu: 40m
                    memory: 100Mi
                  requests:
                    cpu: 10m
                    memory: 25Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  privileged: false
                  readOnlyRootFilesystem: true
                  runAsNonRoot: true
              serviceAccountName: ibm-commonui-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - common-webui
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - networking.k8s.io
          resources:
          - '*'
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operators.ibm.com
          resources:
          - commonwebuis
          - legacyheaders
          - commonwebuis/finalizers
          - legacyheaders/finalizers
          - legacyheaders/status
          - commonwebuis/status
          verbs:
          - '*'
        - apiGroups:
          - foundation.ibm.com
          resources:
          - navconfigurations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: ibm-commonui-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - IBM
  - Cloud
  - Web Console
  - Common Services
  labels:
    name: ibm-commonui-operator
  links:
  - name: GitHub
    url: https://github.com/IBM/ibm-commonui-operator
  maintainers:
  - email: ericabr@us.ibm.com
    name: Erica Brown
  maturity: alpha
  provider:
    name: IBM
  replaces: ibm-commonui-operator.v1.1.0
  version: 1.2.0
