apiVersion: foundation.ibm.com/v1
kind: NavConfiguration
metadata:
  labels:
    name: icp4i
  name: icp4i
spec:
  header:
    logoUrl: "/common-nav/graphics/ibm-cloudpak-integration.svg"
    logoAltText: "Cloud Pak for Integration"
    disabledItem: ['catalog', 'createResource', 'bookmark']
  navItems:
    - id: "metering"
      label: "Metering"
      url: "/metering/dashboard?ace_config={ 'showClusterData': false }&dashboard=cpi.icp.main&useNav=icp4i"
      namespace: "ibm-common-services"
      serviceName: "metering-ui"
      serviceId: "metering-ui"
      parentId: "administer"
      detectionServiceName: "true"
    - id: "monitoring"
      label: "Monitoring"
      url: "/grafana"
      namespace: "ibm-common-services"
      serviceName: "monitoring-prometheus"
      serviceId: "monitoring-ui"
      parentId: "administer"
      target: "_blank"
      detectionServiceName: "true"
      isAuthorized:
        - "Administrator"
        - "ClusterAdministrator"
        - "Operator"
    - id: "releases"
      label: "Helm Releases"
      url: "/catalog/instances?useNav=icp4i"
      parentId: "administer"
      serviceId: "catalog-ui"
      detectionServiceName: true
      serviceName: "catalog-ui"
      namespace: "ibm-common-services"
    - id: "repos"
      label: "Helm Repositories"
      url: "/catalog/repositories?useNav=icp4i"
      parentId: "administer"
      serviceId: "catalog-ui"
      detectionServiceName: true
      serviceName: "catalog-ui"
      namespace: "ibm-common-services"
    - id: "administer"
      label: "Administer"
      iconUrl: "{{ .Values.ingressPath }}/graphics/administer.svg"
    - id: "id-access"
      label: "Identity and Access"
      url: "{{ .Values.ingressPath }}/identity-access?useNav=icp4i"
      parentId: "administer"
      serviceId: "webui-nav"
    - id: "logging"
      label: "Logging"
      url: "/kibana"
      serviceId: "kibana"
      target: "logging"
      serviceName: "kibana"
      namespace: "ibm-common-services"
      detectionServiceName: "true"
      parentId: "administer"
      
