apiVersion: operators.ibm.com/v1alpha1
kind: CommonWebUIService
metadata:
  name: example-commonwebuiservice
  namespace: default
spec:
  globalConfig:
    CLOUDPAK_VERSION: 3.2.4
    authServiceUrl: https://icp-management-ingress:443/idauth
    cfcRouterUrl: https://icp-management-ingress:443
    identityProviderUrl: https://icp-management-ingress:443/idprovider
    cluster_name: mycluster
    default_admin_user: admin
    router_https_port: 443
    session_polling_interval: 5000
  uiConfig:
    ingressPath: /common-nav2
    cpuLimits: 300m
    cpuMemory: 200Mi
    requestLimits: 300m
    requestMemory: 200Mi
    imageRegistry: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64
    imageTag: 1.1.0
    serviceName: common-web-ui
  operatorVersion: 1.1.0

  
