apiVersion: operators.ibm.com/v1alpha1
kind: LegacyHeader
metadata:
  name: example-legacyheaderservice
spec:
  legacyGlobalUIConfig:
    cloudPakVersion: 3.2.4
    authServiceURL: https://icp-management-ingress:443/idauth
    routerURL: https://icp-management-ingress:443
    identityProviderURL: https://icp-management-ingress:443/idprovider
    clusterName: mycluster
    defaultAdminUser: admin
    enterpriseLDAP: ''
    defaultAuth: ''
    enterpriseSAML: ''
    osAuth: ''
    routerHTTPSPort: 443
    sessionPollingInterval: 5000
  legacyConfig:
    ingressPath: /header
    cpuLimits: 300m
    cpuMemory: 200Mi
    requestLimits: 300m
    requestMemory: 200Mi
    imageRegistry: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64
    imageTag: 3.2.4
    serviceName: platform-header
    legacyDocURL: /header/api/v1/doc
    legacyLogoAltText: IBM Cloud Pak
    legacyLogoHeight: 355px
    legacyLogoPath: "/common-nav/graphics/ibm-cloudpack-logo.svg"
    legacyLogoWidth: 18px
    legacySupportURL: /path/to/support.html
  operatorVersion: 1.1.0
