channels:
- currentCSV: ibm-commonui-operator.v1.2.3
  name: beta
- currentCSV: ibm-commonui-operator.v1.2.3
  name: dev
- currentCSV: ibm-commonui-operator.v1.2.3
  name: stable-v1
defaultChannel: stable-v1
packageName: ibm-commonui-operator-app
