apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "foundation.ibm.com/v1",
          "kind": "NavConfiguration",
          "metadata": {
            "labels": {
              "default": "true",
              "name": "common-web-ui-config"
            },
            "name": "common-web-ui-config"
          },
          "spec": {
            "about": {
              "copyright": "© 2018, 2019, 2020 IBM. All rights reserved.",
              "edition": "Enterprise",
              "licenses": [
                "Ansible: © 2017 Red Hat, Inc., http://www.redhat.com; © Henry Graham (hzgraham) \u003cHenry.Graham@mail.wvu.edu\u003e",
                "calico-bird: © 1998–2008, Martin Mares \u003cmj@ucw.cz\u003e; © 1998–2000, Pavel Machek \u003cpavel@ucw.cz\u003e; © 1998–2008, Ondrej Filip \u003cfeela@network.cz\u003e; © 2009–2013,  CZ.NIC z.s.p.o.",
                "chrony: © Richard P. Curnow  1997-2003, GPL v2",
                "collectd, © 2017-2018, version 5.7.2, GPL v2, \u003chttps://github.com/collectd/collectd/tree/collectd-5.7.2\u003e",
                "crudini: © Pádraig Brady \u003cP@draigBrady.com\u003e",
                "Galera-3: © 2007–2014 Codership Oy \u003cinfo@codership.com\u003e",
                "glusterfs: © 2010–2013+ James Shubin \u003chttps://ttboj.wordpress.com/\u003e",
                "haproxy: © 2000–2013  Willy Tarreau \u003cw@1wt.eu\u003e",
                "heketi v6.0.0: © 2015 The heketi Authors, GPL v2",
                "heketi v8.0.0: © 2015 The heketi Authors, GPL v2",
                "heketi-master/apps.app.go: © 2015 The heketi Authors",
                "heketi-master/client/api/go-client/backup.go: © 2016 The heketi Authors",
                "heketi-master/doc/man/heketi-cli.8: © 2016 The heketi Authors",
                "heketi-master/extras/docker/gluster/gluster-setup.sh: © 2016 Red Hat, Inc. \u003chttp://www.redhat.com\u003e",
                "ieee-data: © 2013 Luciano Bello \u003cluciano@debian.org\u003e",
                "javax.mail: © 2017 Oracle and/or its affiliates. All rights reserved.",
                "keepalived: © 2001-2017 Alexandre Cassen \u003cacassen@gmail.com\u003e",
                "libonig2: © 2006–2008 Max Kellermann \u003cmax@duempel.org\u003e; © 2014–2015 Jörg Frings-Fürst \u003cdebian@jff-webhosting.net\u003e",
                "libtomcrypt: © 2004 Sam Hocevar \u003csam@hocevar.net\u003e, GPL v2",
                "mariadb-common: © 2018 MariaDB. All rights reserved.",
                "mariaDB: © 2018 MariaDB. All rights reserved. \u003chttps://mariadb.com/\u003e",
                "mariadb-server: © 2018 MariaDB. All rights reserved.",
                "minitar: © 2004 Mauricio Julio Fernandez Pradier and Austin Ziegler",
                "MongoDB: © 2007 Free Software Foundation, Inc. \u003chttp://fsf.org/\u003e",
                "nvmi-cli: © 1989, 1991 Free Software Foundation, Inc., GPL v2",
                "OpenJDK: © 2018 Oracle Corporation and/or its affiliates",
                "openshift-mariadb-galera: © 2007 Free Software Foundation, Inc. \u003chttp://fsf.org/\u003e",
                "percona-xtrabackup: © 2006–2018 Percona LLC.",
                "pwgen: © Christian Thöing \u003cc.thoeing@web.de\u003e",
                "rdoc: © 2001–2003 Dave Thomas, The Pragmatic Programmers",
                "readline: © Chet Ramey \u003cchet.ramey@case.edu\u003e",
                "John the Ripper password cracker: © 1996–2013 by Solar Designer \u003csolar@openwall.com\u003e",
                "spdx-exceptions: © 2018 SPDX Workgroup a Linux Foundation Project. All rights reserved.",
                "socat: © 2001–2010 Gerhard Rieger",
                "sshpass: © 2006, 2008 Lingnu Open Source Consulting Ltd. \u003chttp://www.lingnu.com\u003e",
                "timelimit: © 2001, 2007 - 2010  Peter Pentchev, GPL v2",
                "ua-parser-js: © 2012-2018 Faisal Salman \u003cf@faisalman.com\u003e, GPL v2",
                "ubuntu-cloud-keyring: © 2010 Michael Vogt \u003cmichael.vogt@canonical.com\u003e",
                "unboundid-ldapsdk: © 2015 UnboundID. The LDAP SDK for Java is developed by UnboundID. \u003cinfo@unboundid.com\u003e",
                "xmpp4r: © Lucas Nussbaum \u003clucas@lucas-nussbaum.net\u003e, Stephan Maka \u003cstephan@spaceboyz.net\u003e, and others.",
                "module-assistant: © 2003-2008 Eduard Bloch \u003cblade@debian.org\u003e, version 0.11.8, GPL v2; © 2009 Cyril Brulebois \u003ckibi@debian.org\u003e, version 0.11.8, GPL v2; © 2013-2018 Andreas Beckmann \u003canbe@debian.org\u003e, version 0.11.8, GPL v2",
                "module-init-tools: © 2011 ProFUSION embedded systems, version 22, GPL v2",
                "thin: © 2017 Marc-Andre Cournoyer \u003cmacournoyer@gmail.com\u003e, version 1.7.2, GPL v2",
                "gosu, © 1999-2014, version 1.1, GPL v3",
                "mercurial (Python), © 2006-2018 ,version v4.5.3, GPL v2",
                "garden-runc, © 2015-Present CloudFoundry.org Foundation, Inc. All Rights Reserved, version 1.17.0, GPLv2",
                "libtomcrypt0, © 2003-2007 Tom St Denis \u003ctomstdenis@gmail.com\u003e, version 1.17-7, GPLv2",
                "console-setup-min, © 1999,2000,2001,2002,2003,2006,2007,2008,2009,2010,2011 Anton Zinoviev, \u003canton@lml.bas.bg\u003e,version 1.108, GPLv2",
                "dracut, © 2009 Harald Hoyer \u003charald@redhat.com\u003e, version 044+3-3, GPLv2",
                "dracut-core, © 2009 Harald Hoyer \u003charald@redhat.com\u003e, version 044+3-3, GPLv2",
                "g++, version 5.4.0-6ubuntu, GPL v2",
                "libstdc++6, version 5.4.0-6ubuntu, GPL v3",
                "libstdc++-5-dev, version 5.4.0-6ubuntu, GPL v3",
                "docker-engine-selinux, version 3b5fac4, GPLv2",
                "unorm, version 1.5.0, GPL v2",
                "psmisc, version 22.20, GPL v2",
                "lvm2-devel, version 2.0.2, GPL v2",
                "nfs-utils, version 1.3, GPL v2",
                "popt-static, version 1.13, GPL v2",
                "sysvinit-tools, version 2.88, GPL v2",
                "stunnel, version 5.53, GPL v2",
                "stunnel, version 5.39, GPL v2",
                "LVM2, version 2.02.180-10.el7_6.2, GPL v2",
                "sysdig, version 2c43237, GPL",
                "chisels, version 9722dbc, GPL",
                "MongoDB, version 4.0.12, SSPL",
                "ffi (Ruby Gem), 1.11.1, GPL",
                "inotify-tools, v3.14, GPL v2",
                "logrotate, v3.8.6, GPL v2",
                "checker-qual, version 2.0.0, GPLv2"
              ],
              "logoAltText": "IBM Cloud Pak",
              "logoUrl": "IBM Cloud Pak",
              "version": "1.1.0"
            },
            "header": {
              "logoAltText": "IBM Cloud Pak",
              "logoHeight": "47px",
              "logoUrl": "/common-nav/api/graphics/logincloudpak.svg",
              "logoWidth": "190px"
            },
            "login": {
              "loginDialog": {
                "acceptText": "Your acceptance text here",
                "dialogText": "You must set your dialog for this environment",
                "enable": false,
                "headerText": "Header text here"
              },
              "logoAltText": "/common-nav/api/graphics/logincloudpak.svg",
              "logoHeight": "47px",
              "logoUrl": "IBM Cloud Pak",
              "logoWidth": "190px"
            },
            "navItems": [
              {
                "iconUrl": "/common-nav/graphics/monitor-health.svg",
                "id": "monitor-health",
                "label": "Monitor Health"
              },
              {
                "detectionServiceName": true,
                "id": "metering",
                "label": "Metering",
                "namespace": "kube-system",
                "parentId": "administer",
                "serviceId": "metering-ui",
                "serviceName": "metering-ui",
                "url": "/metering/dashboard?ace_config={ 'showClusterData': false }\u0026dashboard=cpi.icp.main"
              },
              {
                "detectionServiceName": true,
                "id": "monitoring",
                "isAuthorized": [
                  "Administrator",
                  "ClusterAdministrator",
                  "Operator"
                ],
                "label": "Monitoring",
                "namespace": "kube-system",
                "parentId": "monitor-health",
                "serviceId": "monitoring-ui",
                "serviceName": "monitoring-prometheus",
                "target": "_blank",
                "url": "/grafana"
              },
              {
                "id": "releases",
                "label": "Helm Releases",
                "parentId": "monitor-health",
                "serviceId": "catalog-ui",
                "url": "/catalog/instances"
              },
              {
                "id": "repos",
                "label": "Helm Repositories",
                "parentId": "administer",
                "serviceId": "catalog-ui",
                "url": "/catalog/repositories"
              },
              {
                "iconUrl": "/common-nav/graphics/administer.svg",
                "id": "administer",
                "label": "Administer"
              },
              {
                "id": "id-access",
                "label": "Identity and Access",
                "parentId": "administer",
                "serviceId": "webui-nav",
                "url": "/common-nav/identity-access"
              },
              {
                "detectionServiceName": true,
                "id": "logging",
                "label": "Logging",
                "namespace": "kube-system",
                "parentId": "administer",
                "serviceId": "kibana",
                "serviceName": "kibana",
                "target": "logging",
                "url": "/kibana"
              }
            ]
          }
        },
        {
          "apiVersion": "foundation.ibm.com/v1",
          "kind": "NavConfiguration",
          "metadata": {
            "labels": {
              "name": "icp4i"
            },
            "name": "icp4i"
          },
          "spec": {
            "header": {
              "disabledItem": [
                "catalog",
                "createResource",
                "bookmark"
              ],
              "logoAltText": "Cloud Pak for Integration",
              "logoUrl": "/common-nav/graphics/ibm-cloudpak-integration.svg"
            },
            "navItems": [
              {
                "detectionServiceName": "true",
                "id": "metering",
                "label": "Metering",
                "namespace": "kube-system",
                "parentId": "administer",
                "serviceId": "metering-ui",
                "serviceName": "metering-ui",
                "url": "/metering/dashboard?ace_config={ 'showClusterData': false }\u0026dashboard=cpi.icp.main\u0026useNav=icp4i"
              },
              {
                "detectionServiceName": "true",
                "id": "monitoring",
                "isAuthorized": [
                  "Administrator",
                  "ClusterAdministrator",
                  "Operator"
                ],
                "label": "Monitoring",
                "namespace": "kube-system",
                "parentId": "administer",
                "serviceId": "monitoring-ui",
                "serviceName": "monitoring-prometheus",
                "target": "_blank",
                "url": "/grafana"
              },
              {
                "id": "releases",
                "label": "Helm Releases",
                "parentId": "administer",
                "serviceId": "catalog-ui",
                "url": "/catalog/instances?useNav=icp4i"
              },
              {
                "id": "repos",
                "label": "Helm Repositories",
                "parentId": "administer",
                "serviceId": "catalog-ui",
                "url": "/catalog/repositories?useNav=icp4i"
              },
              {
                "iconUrl": "{{ .Values.ingressPath }}/graphics/administer.svg",
                "id": "administer",
                "label": "Administer"
              },
              {
                "id": "id-access",
                "label": "Identity and Access",
                "parentId": "administer",
                "serviceId": "webui-nav",
                "url": "{{ .Values.ingressPath }}/identity-access?useNav=icp4i"
              },
              {
                "detectionServiceName": "true",
                "id": "logging",
                "label": "Logging",
                "namespace": "kube-system",
                "parentId": "administer",
                "serviceId": "kibana",
                "serviceName": "kibana",
                "target": "logging",
                "url": "/kibana"
              }
            ]
          }
        },
        {
          "apiVersion": "operators.ibm.com/v1alpha1",
          "kind": "CommonWebUI",
          "metadata": {
            "name": "example-commonwebui"
          },
          "spec": {
            "commonWebUIConfig": {
              "cpuLimits": "300m",
              "cpuMemory": "200Mi",
              "imageRegistry": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64",
              "imageTag": "1.1.0",
              "ingressPath": "/common-nav",
              "requestLimits": "300m",
              "requestMemory": "200Mi",
              "serviceName": "common-web-ui"
            },
            "globalUIConfig": {
              "authServiceURL": "https://icp-management-ingress:443/idauth",
              "cloudPakVersion": "3.2.4",
              "clusterName": "mycluster",
              "defaultAdminUser": "admin",
              "defaultAuth": "",
              "enterpriseLDAP": "",
              "enterpriseSAML": "",
              "identityProviderURL": "https://icp-management-ingress:443/idprovider",
              "osAuth": "",
              "routerHTTPSPort": 443,
              "routerURL": "https://icp-management-ingress:443",
              "sessionPollingInterval": 5000
            },
            "operatorVersion": "1.1.0"
          }
        },
        {
          "apiVersion": "operators.ibm.com/v1alpha1",
          "kind": "LegacyHeader",
          "metadata": {
            "name": "example-legacyheaderservice"
          },
          "spec": {
            "legacyConfig": {
              "cpuLimits": "300m",
              "cpuMemory": "200Mi",
              "imageRegistry": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64",
              "imageTag": "3.2.4",
              "ingressPath": "/header",
              "legacyDocURL": "/header/api/v1/doc",
              "legacyLogoAltText": "IBM Cloud Pak",
              "legacyLogoHeight": "355px",
              "legacyLogoPath": "/common-nav/graphics/ibm-cloudpack-logo.svg",
              "legacyLogoWidth": "18px",
              "legacySupportURL": "/path/to/support.html",
              "requestLimits": "300m",
              "requestMemory": "200Mi",
              "serviceName": "platform-header"
            },
            "legacyGlobalUIConfig": {
              "authServiceURL": "https://icp-management-ingress:443/idauth",
              "cloudPakVersion": "3.2.4",
              "clusterName": "mycluster",
              "defaultAdminUser": "admin",
              "defaultAuth": "",
              "enterpriseLDAP": "",
              "enterpriseSAML": "",
              "identityProviderURL": "https://icp-management-ingress:443/idprovider",
              "osAuth": "",
              "routerHTTPSPort": 443,
              "routerURL": "https://icp-management-ingress:443",
              "sessionPollingInterval": 5000
            },
            "operatorVersion": "1.1.0"
          }
        }
      ]
    capabilities: Basic Install
  name: ibm-commonui-operator.v1.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CommonWebUI is the Schema for the commonwebuis API
      kind: CommonWebUI
      name: commonwebuis.operators.ibm.com
      version: v1alpha1
      displayName: CommonWebUI service
    - description: LegacyHeader is the Schema for the legacyHeader API
      kind: LegacyHeader
      name: legacyheaders.operators.ibm.com
      version: v1alpha1
      displayName: LegacyHeader service
      description: NavConfiguration for the CommonWebUI service which returns custom nav configurations
      kind: NavConfiguration
      name: navconfigurations.foundation.ibm.com
      version: v1
      displayName: NavConfiguration service
  description: Placeholder description
  displayName: IBM Commonui Operator
  install:
    spec:
      deployments:
      - name: ibm-commonui-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-commonui-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-commonui-operator
            spec:
              containers:
              - command:
                - ibm-commonui-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-commonui-operator
                image: quay.io/opencloudio/ibm-commonui-operator
                imagePullPolicy: Always
                name: ibm-commonui-operator
                resources: {}
              serviceAccountName: ibm-commonui-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - common-webui
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - networking.k8s.io
          resources:
          - '*'
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operators.ibm.com
          resources:
          - commonwebuis
          - legacyheaders
          - commonwebuis/finalizers
          - legacyheaders/finalizers
          verbs:
          - '*'
        serviceAccountName: ibm-commonui-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider:
    name: IBM
  replaces: ibm-commonui-operator.v0.0.0
  version: 1.1.0
